
name: George Pearson
description: Development and scientific musings
url: "https://georgepearson.co.uk"
exclude: ["node_modules", "gulpfile.js", "package.json"]
plugins: [jekyll-paginate]
paginate: 2
markdown: kramdown
highlighter: rouge