
name: George Pearson
description: Development and scientific musings
baseurl: ""
url: ""
exclude: ["node_modules", "gulpfile.js", "package.json"]
plugins: [jekyll-paginate]
paginate: 2
markdown: kramdown